name: Code Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: ShellCheck (Bash)
        run: |
          sudo apt-get install shellcheck
          shellcheck *.sh

      - name: Set up PowerShell
        uses: Amadevus/pwsh-script@v2.0.3
        with:
          powershell-version: '7.2'

      - name: PSScriptAnalyzer (PowerShell)
        shell: pwsh
        run: |
          Install-Module -Name PSScriptAnalyzer -Force
          Invoke-ScriptAnalyzer -Path *.ps1 -Severity Warning

